# Generated by Django 3.2 on 2021-04-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_kodu', models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003')], max_length=12, verbose_name='Firma Kodu')),
                ('firma', models.CharField(choices=[('Otokoç', 'Otokoç'), ('Ayder', 'Ayder'), ('Tan Oto', 'Tan Oto')], max_length=45, verbose_name='Firma Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Limak_Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limak_kodu', models.CharField(choices=[('000', '000'), ('001', '001'), ('002', '002')], max_length=12, verbose_name='Limak Kodu')),
                ('limak_sirketi', models.CharField(choices=[('Limak Holding', 'Limak Holding'), ('Limak İnşaat', 'Limak inşaat'), ('Limak Yatırım', 'Limak Yatırım')], max_length=35, verbose_name='Limak Şirketleri')),
            ],
        ),
        migrations.CreateModel(
            name='Sozlesme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sözlesme_no', models.CharField(max_length=3, verbose_name='Sözlesme Numarası')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sozlesmeler.firma')),
                ('limak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sozlesmeler.limak_sirket')),
            ],
        ),
    ]
